name: sqlcheck workflow2
on: push

jobs:
  sqlcheck:
    name: sqlcheck job
    runs-on: ubuntu-latest
    steps:
    #- uses: actions/checkout@master
    - uses: yokawasa/action-sqlcheck@sql-syntax-check
      id: sqlcheck
      with:
        post-comment: true
        risk-level: 3
        verbose: true
        token: ${{ secrets.GITHUB_TOKEN }}
        postfixes: |
          sql
          sqlx
          schema
        directories: |
          sql
          build/sql_dir
          tests/sql_dir
    - name: Get output
      run: echo "Issues found in previous step"
      if: steps.sqlcheck.outputs.issue-found
