name: Workflow1

on:
  push:
    branches:
      - trigger-workflow

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      pat_token: ${{ secrets.GITHUB_TOKEN }}


    steps:
      - uses: actions/checkout@v3          
      - name: Trigger workflow using curl
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: pat_token" \
          https://api.github.com/repos/RutujaK2211/testAzure/actions/workflows/workflow2.yml/dispatches \
          -d '{"ref":"refs/heads/master"}'
